# Generated by Django 5.2.1 on 2025-07-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_pedido_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_modificacion',
            new_name='updated',
        ),
    ]
