# Generated by Django 5.2.1 on 2025-05-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_category_alter_brand_options_product_variantproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantproduct',
            name='size',
        ),
    ]
