# Generated by Django 5.2.1 on 2025-06-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_remove_product_category_variantproduct_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantproduct',
            name='image',
        ),
        migrations.AlterField(
            model_name='imagesproductvariant',
            name='image',
            field=models.URLField(max_length=250),
        ),
    ]
