# Generated by Django 5.2.1 on 2025-06-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_remove_variantproduct_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
