# Generated by Django 5.2.1 on 2025-07-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantproduct',
            name='size',
            field=models.PositiveIntegerField(choices=[(38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44')], default=38),
        ),
    ]
